Docs: Document service.rs functions
etesync/etebase-rs pull request #11
Opened 2020-11-11 19:18 UTC by shashwatjolly

2020-11-11 19:30 UTC, tasn commented on src/service.rs
> +    /// Create a new encrypted [Collection] and return a handle to it. This receives the metadata as a byte array.
I think it's better to split it to two lines. Potentially with an empty line in between (like git) to better emphasise the first sentence as the main one.

```
/// Create a new encrypted [Collection] and return a handle to it using raw metadata
///
/// Unlike [create] metadata is expected to be a valid msgpack-encoded metadata object.
///
/// # Arguments:
/// ...

2020-11-11 20:35 UTC, tasn commented on src/service.rs
> -
The extra empty line was on purpose.

2020-11-11 20:52 UTC, tasn commented on src/service.rs
> +    /// Create an upload transaction for the supplied [Item]s with a list of items as dependencies. This will fail if the dependencies have changed remotely.
Forgot to split this to two lines.

2020-11-11 21:24 UTC, tasn commented on src/service.rs
> +    /// Mark the collection as deleted
Maybe in the long description (for this, and for the one for item) mention that the item is only marked for deletion and still needs to be uploaded?

2020-11-12 14:15 UTC, tasn commented
Note to self: document `meta_generic`

2020-11-12 16:04 UTC, shashwatjolly commented
@tasn Documentation for `Client` is remaining

2020-11-12 19:01 UTC, tasn requested changes
Wow, that took me a while! Looks great overall, good job! I just made some suggestions.
The overall comment you need to keep in mind: the docs are here to simplify using the API, so they should:
1. Be concise, so they are easy to read.
2. Be explicit rather than vague
3. Simple, so don't add new terminology unless you have to

2020-11-12 19:01 UTC, tasn commented on src/service.rs
> +/// Items can hold whatever kind of data is needed in the form of a byte array
Needed? Whatever?

How about replacing this and the next with:
```
Items have two pieces of data associated with them:
* [metadata](ItemMetadata) - contains meta information like name and modification time.
* Content - a buffer containing arbitrary binary data.
```

2020-11-12 19:01 UTC, tasn commented on src/service.rs
> +/// Items can hold whatever kind of data is needed in the form of a byte array
Same for collections if you did the same for that.

2020-11-13 12:02 UTC, merged